config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  unauthenticated :user do
    devise_scope :user do
      root 'users/sessions#new'
     
    end
  end

  root 'rooms#show'

  resources :room_messages, only: %i[index create]
  resources :users, only: :index
  resources :rooms, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_messages, dependent: :destroy,
                           inverse_of: :room
  has_many :users, through: :room_messages                         
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  validates :message, presence: true

  belongs_to :room, inverse_of: :room_messages
  belongs_to :user

  before_save :save_username

  def self.all_messages
    Redis.new.hgetall('room_messages')
  end

  private

  def save_username
    self.username = user.username
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, uniqueness: true, presence: true

  has_many :room_messages,
           dependent: :destroy

  def online?
    Redis.new.get("user_#{self.id}_online").present?
  end

  def need_logout?
    Redis.new.get("logout_#{self.id}").present?
  end

  def self.online_users
    Redis.new.hgetall('online_users')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :custom_logout
  skip_before_action :verify_authenticity_token

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username])
  end

  def custom_logout
    if current_user&.need_logout?
      Redis.new.del("logout_#{current_user.id}")
      sign_out(current_user)
      redirect_to root_path
    end
  end
end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
  before_action :load_entities

  def index
    @room_messages = Redis.new.hgetall('room_messages')
  end
  def create
    @room_message = RoomMessage.create user: current_user,
                                       room: @room,
                                       message: params.dig(:room_message, :message)
    Redis.new.hset('room_messages', @room_message.id, @room_message.message)
    ActionCable.server.broadcast 'room', @room_message
  end
  protected
  def load_entities
    @room = Room.find params.dig(:room_message, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :load_entities

  def index
    @rooms = Redis.new.hgetall('rooms')
  end
 def create 
 end

  def show
    @room_message = RoomMessage.new(room: @room)
     @room_messages = @room.room_messages.includes(:user)
  end
  
  protected

  def load_entities
    @rooms = Room.joins(:users).where(users: { id: current_user.id }).uniq
    @room = params[:id].present? ? Room.find(params[:id]) : Room.first
  end

  def permitted_parameters
    params.require(:room).permit(:name)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new
    @users = User.order(:id).collect { |user| [user.username, user.id] }
    super
  end

  def create
    user = User.find(params[:id])
    if user.present? && user.valid_password?(params[:password])
      sign_in(user)
      Redis.new.del("logout_#{current_user.id}")
      broadcast(true)
      send_connect_message("#{current_user.username} connected") unless current_user.online?
      redirect_to root_path
    else
      redirect_to new_user_session_path
    end
  end

  def destroy
    broadcast(false)
    send_connect_message("#{current_user.username} left") unless current_user.need_logout?
    sign_out(current_user)
    redirect_to root_path
  end

  def send_connect_message(message)
    room = Room.find_by(general: true)
    room_message = RoomMessage.create(room: room, user: current_user, message: message,
                                      connected_message: true)
    ActionCable.server.broadcast 'room', room_message
  end

  private

  def broadcast(online)
    ActionCable.server.broadcast 'appearance', user_id: current_user.id, online: online
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    Redis.new.hgetall('online_users')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def last_message(room)
    room.room_messages.last
  end

  def current_user_owner?(message)
    message.user == current_user
  end

  def check_position(message)
    current_user_owner?(message) ? 'text-right' : 'text-left'
  end

  def current_chat(id, room_id)
    id.to_i == room_id ? 'bg-white' : ''
  end

  def first_chat(id, room)
    id.nil? && room == Room.first ? 'bg-white' : ''
  end

  def opposite_user(room, user_id)
    id = room.name.split(':').map(&:to_i).delete_if { |i| i == user_id }.first
    User.find(user_id) unless room.general?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def check_online(user)
    user.online? ? 'bg-success' : 'bg-gray'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatRoom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <!-- <div class="container"> -->
      <!-- <div class="row"> -->
        <!-- <div class="col-12"> -->
          <%= render partial: 'shared/navigation_bar' %>
          <!-- <div class="my-3"> -->
          <div id='root'>
            <div class="full-height bg-light">
            <%= yield %>
          </div>
        </div>
      <!-- </div> -->
    <!-- </div> -->
  </body>
</html>

app/views/rooms/_rooms.html.erb
<div class="messages-box flex flex-1">
  <div class="list-group rounded-0">
    <% @rooms.each do |room| %>
      <%= link_to room_path(room), class: 'link-chat-block' do %>
        <div class='chat-list-item custom-chat-item d-flex align-items-start rounded <%= "#{current_chat(params[:id], room.id)}" "#{first_chat(params[:id], room)}" %>'>
          <div class="align-self-center mr-3">
            <div class="rounded-circle <%= check_online(opposite_user(room, current_user.id)) unless room.general? %>" style="width: 8px; height: 8px;" data-user-id=<%= opposite_user(room, current_user.id).id unless room.general? %>></div>
          </div>
          <div class="align-self-center mr-3">
            <div class="overflow-hidden rounded-circle">
              <% if room.name? %>
                <svg width="32" height="32" viewbox="0 0 1651 1651" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <rect width="1651" height="1651" rx="14" fill="white"></rect>
                  <path
                    d="M495.286 1098.96L497.967 1070.86L478.04 1050.88C408.572 981.233 368 891.771 368 795.344C368 585.371 565.306 402 826 402C1086.69 402 1284 585.371 1284 795.344C1284 1005.32 1086.69 1188.69 826 1188.69V1248.69L825.913 1188.69C779.837 1188.75 733.952 1182.77 689.432 1170.9L667.26 1164.98L646.8 1175.37C620.731 1188.61 562.74 1213.98 467.32 1235.35C480.554 1191.83 490.95 1144.39 495.286 1098.96Z"
                    stroke="url(#paint0_linear)"
                    stroke-width="120"></path>
                  <defs>
                    <lineargradient id="paint0_linear" x1="662.312" y1="397.956" x2="416.164" y2="1678.7" gradientunits="userSpaceOnUse">
                      <stop stop-color="#7514FB"></stop>
                      <stop offset="0.624243" stop-color="#F26D41"></stop>
                      <stop offset="1" stop-color="#F43B4B"></stop>
                    </lineargradient>
                  </defs>
                </svg>
              <% else %>
              <% end %>
            </div>
          </div>
          <div class="media-body overflow-hidden">
            <h5 class="text-truncate font-size-14 mb-1">
              <%= room.name? ? room.name : opposite_user(room, current_user.id).username %>
            </h5>
            <p class="text-truncate mb-0 chat-list-last-message-<%= room.id %>">
              <%= last_message(room).message %>
            </p>
          </div>
          <div class="font-size-11"><%= last_message(room).created_at.strftime('%H:%M %p') %></div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="chat-main-block">
  <div class="container py-5 px-4">
    <div class="custom-chat-body chat-body row overflow-hidden shadow bg-dark rounded">
      <div class="col-4 px-0">
        <div class="chat-list-container flex-column d-flex pr-4">
          <div class="py-2">
            <p class="h5 mb-0 py-1 chats-title text-white">Chats</p>
          </div>
          <%= render 'rooms' %>
        <div class="row no-gutters align-items-center pl-4 pr-2 pb-3" style="height: inherit; flex: 0 1 0%; min-height: 50px;">
          <div class="col-8 d-flex align-items-center ">
            <div class="align-self-center mr-3">
            </div>
            <div class="media-body ">
              <h5 class="font-size-14 mt-0 mb-1 text-white"><%= current_user.username %></h5>
              <div class="d-flex align-items-center">
                <div class="rounded-circle bg-success" style="width: 8px; height: 8px; opacity: 1;"></div>
                <p class="ml-2 text-muted mb-0 ">Active Members</p>
              </div>
            </div>
          </div>
          <div class="col-4 text-danger text-right" style="cursor: pointer;">
            <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 16 16" width="1em" height="1em" fill="currentColor">
              <path fill-rule="evenodd" d="M5.578 4.437a5 5 0 1 0 4.922.044l.5-.866a6 6 0 1 1-5.908-.053l.486.875z"></path>
              <path fill-rule="evenodd" d="M7.5 8V1h1v7h-1z"></path>
            </svg>
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'color-red' %>

            </div>
        </div>
      </div>
      </div>
      <div class="col-8 px-0 flex-column bg-white rounded-lg">
      <div class="px-4 py-4" style="border-bottom: 1px solid rgb(238, 238, 238);">
        <h2 class="font-size-15 mb-0 "><%= @room.name? ? @room.name : opposite_user(@room, current_user.id).username %></h2>
      </div>

      <div class="main-chat-box chat-box-wrapper position-relative d-flex max-height-30">
        <div class="px-4 pt-5 chat-box-custom w-100">
          <div class="chat" data-channel-subscribe="room" data-room-id="<%= @room.id %>">
            <% @room_messages.each do |message| %>
              <div id='room-messages-count' data-messages-count=<%= @room_messages.count %>></div>
              <% if message.connected_message? %>
                <p class="mb-2 fs-6 fw-light fst-italic text-dark-50 text-center message-block" style="opacity: 0.8; font-size: 14px;"><%= message.message %></p>
              <% else %>
                <div class="d-flex message-block">
                  <% if current_user_owner?(message) %>
                    <div style="flex: 1 1 0%;"></div>
                  <% end %>
                  <div class="<%= check_position(message) %> mb-4" style='width: 50%'>
                    <div class="conversation-list d-inline-block px-3 py-2" style="border-radius: 12px; background-color: rgba(85, 110, 230, 0.2);">
                      <div class="ctext-wrap">
                        <div class="conversation-name text-dark d-flex align-items-center mb-1">
                          <div class="mr-2" style="font-weight: 600; cursor: pointer;"><%= message.user.username %></div>
                          <% unless current_user_owner?(message) %>
                            <div class="rounded-circle <%= check_online(message.user) %>" style="width: 7px; height: 7px; opacity: 1;"></div>
                          <% end %>
                        </div>
                        <p class="text-left"><%= message.message %></p>
                        <p class="chat-time mb-0">
                          <svg width="12" height="12" class="prefix__MuiSvgIcon-root prefix__jss80 prefix__MuiSvgIcon-fontSizeLarge" viewbox="0 0 24 24" aria-hidden="true">
                            <path d="M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8z"></path>
                            <path d="M12.5 7H11v6l5.25 3.15.75-1.23-4.5-2.67z"></path>
                          </svg>
                          <%= message.created_at.strftime("%B %d %Y, %l:%M%P") %>
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="p-3 chat-input-section">
        <%= form_for @room_message, url: url_for(controller: 'room_messages', action: 'create'), html: { class: 'row' }, remote: true do |form| %>
          <div class="col">
            <div class="position-relative">
              <%= form.text_field :message, wrapper: false, class: 'form-control chat-input', autocomplete: 'off', placeholder: 'Enter Message...' %>
            </div>
          </div>
          <div class="col-auto">
            <%= form.submit 'Send', class: 'btn btn-dark btn-rounded chat-send w-md' do %>
            <% end %>
          </div>
          <%= form.hidden_field :room_id, value: @room.id %>
        <% end %>
      </div>

      </div>
    </div>
  </div>
</div>
<div class="d-none" data-role="message-template">
  <p class="mb-2 fs-6 fw-light fst-italic text-dark-50 text-center hide connected-message-socket" style="opacity: 0.8; font-size: 14px;"><span data-role="message-text"></span></p>
  <div class="d-flex message-socket">
    <div data-message-user-id="<%= current_user.id %>" style="flex: 1 1 0%;" class='hide empty-message-div'></div>
    <div class="mb-4 rooms-show-message-position" style='width: 50%'>
      <div class="conversation-list d-inline-block px-3 py-2" style="border-radius: 12px; background-color: rgba(85, 110, 230, 0.1);">
        <div class="ctext-wrap">
          <div class="conversation-name text-primary d-flex align-items-center mb-1">
            <div class="mr-2" style="font-weight: 600; cursor: pointer;">
              <div data-role="message-username"></div>
            </div>
            <div class="rounded-circle rounded-circle-socket bg-success" style="width: 7px; height: 7px; opacity: 1;"></div>
          </div>
          <p class="text-left"><span class="text-left" data-role="message-text"></span></p>
          <p class="chat-time mb-0">
            <svg width="12" height="12" class="prefix__MuiSvgIcon-root prefix__jss80 prefix__MuiSvgIcon-fontSizeLarge" viewbox="0 0 24 24" aria-hidden="true">
              <path d="M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8z"></path>
              <path d="M12.5 7H11v6l5.25 3.15.75-1.23-4.5-2.67z"></path>
            </svg>
            <span data-role="message-date"></span>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navigation_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <span class="navbar-brand text-dark">ChatRoom</span>
</nav>